/** Build-time only. A verified official compiler archive produces the committed static-musl artifact. */
import { spawnSync } from "node:child_process";
import { createHash } from "node:crypto";
import { chmodSync, existsSync, mkdirSync, mkdtempSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { fileURLToPath } from "node:url";
const root = fileURLToPath(new URL("../", import.meta.url));
if (process.platform !== "linux" || process.arch !== "x64") throw new Error("worker build requires Linux x64");
const verify = process.argv.includes("--verify");
if (process.argv.slice(2).some((arg) => arg !== "--verify")) throw new Error("usage: build-worker.ts [--verify]");
const sha256 = (bytes: Uint8Array | string) => createHash("sha256").update(bytes).digest("hex");
const toolchain = JSON.parse(readFileSync(join(root, "native/toolchain.json"), "utf8")) as {
  version: string;
  url: string;
  sha256: string;
  directory: string;
  target: string;
  flags: string[];
};
const cache = join(tmpdir(), "pi-daddy-native-toolchains");
mkdirSync(cache, { recursive: true });
const archive = process.env.PI_DADDY_WORKER_TOOLCHAIN_ARCHIVE ?? join(cache, `${toolchain.directory}.tar.xz`);
if (!existsSync(archive)) {
  const response = await fetch(toolchain.url, { signal: AbortSignal.timeout(120000) });
  if (!response.ok) throw new Error(`toolchain download failed: ${response.status}`);
  const bytes = Buffer.from(await response.arrayBuffer());
  if (sha256(bytes) !== toolchain.sha256) throw new Error("downloaded toolchain archive hash mismatch");
  writeFileSync(archive, bytes, { flag: "wx" });
}
if (sha256(readFileSync(archive)) !== toolchain.sha256) throw new Error("cached toolchain archive hash mismatch");
const work = mkdtempSync(join(tmpdir(), "pi-daddy-native-build-"));
function run(command: string, args: string[]) {
  const result = spawnSync(command, args, {
    cwd: work,
    env: { ...process.env, SOURCE_DATE_EPOCH: "0", ZIG_GLOBAL_CACHE_DIR: join(work, "zig-cache") },
    stdio: "inherit",
  });
  if (result.status !== 0) throw new Error(`${command} failed: ${result.status ?? result.error}`);
}
try {
  run("tar", ["-xJf", archive, "-C", work]);
  const source = readFileSync(join(root, "native/worker.c"));
  writeFileSync(join(work, "worker.c"), source);
  const compiler = join(work, toolchain.directory, "zig");
  run(compiler, ["cc", "-target", toolchain.target, ...toolchain.flags, "-o", "worker", "worker.c"]);
  const binary = readFileSync(join(work, "worker"));
  // Require ELF64 x86-64 without interpreter or dynamic-linker program headers.
  if (binary.toString("hex", 0, 6) !== "7f454c460201" || binary.readUInt16LE(18) !== 62)
    throw new Error("worker is not an ELF64 x86-64 artifact");
  const programHeaders = Number(binary.readBigUInt64LE(32));
  for (let i = 0; i < binary.readUInt16LE(56); i++) {
    const type = binary.readUInt32LE(programHeaders + i * binary.readUInt16LE(54));
    if (type === 2 || type === 3) throw new Error("worker unexpectedly requires dynamic linking");
  }
  const hash = sha256(binary);
  const licenses = [
    ["lib/libc/musl/COPYRIGHT", "musl-COPYRIGHT.txt"],
    ["LICENSE", "zig-MIT.txt"],
  ];
  const outputs = new Map<string, Uint8Array | string>([
    ["native/linux-x64/worker", binary],
    ["native/linux-x64/worker.sha256", hash + "\n"],
    [
      "src/executors/worker-artifact.ts",
      `/** Generated by scripts/build-worker.ts; the loader never trusts a sidecar hash. */\nexport const WORKER_SHA256 = "${hash}";\n`,
    ],
  ]);
  const notices: { path: string; sha256: string; source: string }[] = [];
  for (const [sourcePath, targetName] of licenses) {
    const bytes = readFileSync(join(work, toolchain.directory, sourcePath));
    const path = `THIRD_PARTY_LICENSES/${targetName}`;
    outputs.set(path, bytes);
    notices.push({ path, sha256: sha256(bytes), source: sourcePath });
  }
  outputs.set(
    "native/provenance.json",
    JSON.stringify(
      {
        revision: 1,
        toolchain,
        source: { path: "native/worker.c", sha256: sha256(source) },
        artifact: { path: "native/linux-x64/worker", sha256: hash, bytes: binary.length },
        licenses: notices,
      },
      null,
      2,
    ) + "\n",
  );
  for (const [path, contents] of outputs) {
    const target = join(root, path);
    if (verify) {
      if (!readFileSync(target).equals(Buffer.from(contents)))
        throw new Error(`reproducible worker build differs: ${path}`);
    } else writeFileSync(target, contents);
  }
  if (!verify) chmodSync(join(root, "native/linux-x64/worker"), 0o755);
  if (verify) {
    writeFileSync(join(work, "worker-faults.c"), readFileSync(join(root, "scripts/worker-faults.c")));
    run(compiler, ["cc", "-target", toolchain.target, ...toolchain.flags, "-o", "worker-faults", "worker-faults.c"]);
    run(process.execPath, [join(root, "scripts/check-worker-faults.ts"), join(work, "worker-faults"), hash]);
  }
  console.log(`${verify ? "Verified" : "Built"} static-musl worker ${hash} using Zig ${toolchain.version}`);
} finally {
  rmSync(work, { recursive: true, force: true });
}
