import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { test } from "node:test";
import { Compile } from "typebox/compile";
import { buildLedgerV2ContractFixtures } from "../scripts/generate-ledger-v2-contract.ts";
import { REFUSAL_CODES } from "../src/refusals.ts";
import { buildCheckReceiptLedgerEvent, buildRecord } from "../src/ledger.ts";

const packageRoot = dirname(dirname(fileURLToPath(import.meta.url)));
const contractRoot = join(packageRoot, "contracts", "ledger", "v2");
const schemaPath = join(contractRoot, "ledger-event.schema.json");

async function json(path: string): Promise<unknown> {
  return JSON.parse(await readFile(path, "utf8"));
}

test("the published ledger v2 fixtures are generated by the real event builders", async () => {
  const generated = buildLedgerV2ContractFixtures();
  assert.deepEqual(
    Object.keys(generated).sort(),
    ["capability-decision.json", "check-receipt.json", "child-lifecycle.json", "workspace-lease.json"],
  );
  for (const [name, event] of Object.entries(generated)) {
    assert.deepEqual(await json(join(contractRoot, "fixtures", name)), event, `${name} drifted from its builder`);
  }
});

test("v2 builders refuse digest values that their canonical schema would reject", () => {
  assert.throws(() => buildRecord({
    parentId: "d0", childId: "d0.1", depth: 1, requested: [], parentGrant: [],
    result: { effective: [], denied: [], clipped: [], gatedBlocked: [], universal: [], subsumedBy: [] },
    blocked: false, executor: "process", taskDigest: "", now: new Date(),
  }), /taskDigest must be a SHA-256/);
  assert.throws(() => buildRecord({
    parentId: "d0", childId: "d0.1", depth: 1, requested: [], parentGrant: [],
    result: { effective: [], denied: [], clipped: [], gatedBlocked: [], universal: [], subsumedBy: [] },
    blocked: false, executor: "process", taskDigest: "not-a-sha256", now: new Date(),
  }), /taskDigest must be a SHA-256/);
  assert.throws(() => buildRecord({
    parentId: "d0", childId: "d0.1", depth: 1, requested: [], parentGrant: [],
    result: { effective: [], denied: [], clipped: [], gatedBlocked: [], universal: [], subsumedBy: [] },
    blocked: false, executor: "process", taskDigest: "a".repeat(64),
    definitionDigest: { name: "x", source: "/x", sha256: "not-a-sha256" }, now: new Date(),
  }), /definitionDigest.sha256 must be a SHA-256/);
  assert.throws(() => buildCheckReceiptLedgerEvent({
    childId: "check:x", receiptId: "not-a-sha256", workspaceId: "w", checkId: "x",
    treeSha: "tree", now: new Date(),
  }), /receiptId must be a SHA-256/);
});

test("the canonical schema accepts every generated fixture and rejects unsupported explicit versions", async () => {
  const schema = await json(schemaPath) as Parameters<typeof Compile>[0];
  const validator = Compile(schema);
  for (const [name, event] of Object.entries(buildLedgerV2ContractFixtures())) {
    assert.equal(validator.Check(event), true, `${name}: ${[...validator.Errors(event)].map((error) => error.message).join(", ")}`);
  }
  const fixture = buildLedgerV2ContractFixtures()["capability-decision.json"];
  assert.equal(validator.Check({ ...fixture, ledgerVersion: 3 }), false);
  assert.equal(validator.Check({ ...fixture, extraAuthority: true }), false);
});

test("the schema pins nested correlation, approval, refusal, digest, and null contracts", async () => {
  const schema = await json(schemaPath) as Parameters<typeof Compile>[0] & {
    $defs: { refusalCode: { enum: string[] } };
  };
  assert.deepEqual(schema.$defs.refusalCode.enum, [...REFUSAL_CODES]);
  const validator = Compile(schema);
  const fixtures = buildLedgerV2ContractFixtures();
  const capability = fixtures["capability-decision.json"];
  assert.equal(validator.Check({ ...capability, taskDigest: null }), false);
  assert.equal(validator.Check({ ...capability, correlation: { ...capability.correlation, unknown: "x" } }), false);
  assert.equal(validator.Check({ ...capability, refusal: { code: "NOT_A_REFUSAL", message: "x" } }), false);
  assert.equal(validator.Check({ ...capability, approvalUses: { "tool:bash": { max: 1, remaining: null } } }), false);

  const lifecycle = fixtures["child-lifecycle.json"];
  assert.equal(lifecycle.exitCode, null);
  assert.equal(lifecycle.signal, null);
  assert.equal(validator.Check(lifecycle), true);
  assert.equal(validator.Check({ ...lifecycle, exitCode: "0" }), false);
});
