import {
  buildWorkRevisionEvent, buildWorkSnapshotEvent, buildWorkOccurrenceEvent, buildWorkAcceptanceEvent,
  type WorkProjectionContext, type WorkRevision, type RevisionRef, type WorkRevisionEvent,
  type WorkFrozen, type WorkLedgerEvent, type EventRef,
} from "../src/work-ledger.ts";

// FIXTURE TRUST-BOUNDARY SIMULATION; for selected snapshot; under fixture authority.
// No input claims, file paths or incoming streams are accepted by this controller. The fixed
// declarations below are the host's expected world, not approvals generated by enumerating claims.
export const fixtureNow = new Date("2026-09-06T12:00:00.000Z");
export const fixtureDigest = "a".repeat(64);
type Mutable<T> = T extends ReadonlyArray<infer E> ? Mutable<E>[] : T extends object ? { -readonly [K in keyof T]: Mutable<T[K]> } : T;
/** Test-only detached editable copy; structuredClone does not express removal of readonly in its type. */
export const mutableFixture = <T>(value: T): Mutable<T> => structuredClone(value) as Mutable<T>;
export const fixtureExecution = "exec:00000000-0000-4000-8000-000000000001";
export const fixtureEventRef = (e: WorkFrozen<WorkLedgerEvent>): EventRef => ({ eventId: e.eventId, digest: e.digest });
export const fixtureRevisionRef = (e: WorkFrozen<WorkRevisionEvent>): RevisionRef => {
  const { kind, id, revision, digest } = e.payload.revision;
  return { kind, id, revision, digest };
};
export const fixtureText = (events: readonly WorkFrozen<WorkLedgerEvent>[]) => events.map(e => JSON.stringify(e)).join("\n") + "\n";
export function walkingFixture() {
  const revision = (kind: WorkRevision["kind"], patch: Partial<Omit<WorkRevision, "digest">> = {}) =>
    buildWorkRevisionEvent({ eventId: `fixture:${kind}`, now: fixtureNow, revision: {
      kind, id: kind, scopeId: "scope", revision: 1, predecessor: null, contentDigest: fixtureDigest,
      parent: null, dependencies: [], ownerId: "fixture-owner", permittedEffects: [], policy: null, ...patch,
    } });
  const scope = revision("scope"), policy = revision("policy"), artifact = revision("artifact");
  const intent = revision("goal", { parent: fixtureRevisionRef(scope) });
  const obligation = revision("obligation", { parent: fixtureRevisionRef(intent), policy: fixtureRevisionRef(policy) });
  const binding = { intent: fixtureRevisionRef(intent), obligation: fixtureRevisionRef(obligation),
    artifact: fixtureRevisionRef(artifact), policy: fixtureRevisionRef(policy) };
  const snapshot = buildWorkSnapshotEvent({ eventId: "fixture:snapshot", now: fixtureNow, snapshot: {
    snapshotId: "fixture-selected", scope: fixtureRevisionRef(scope),
    revisions: [policy, artifact, intent, obligation].map(fixtureRevisionRef), bindings: [binding],
  } });
  const occurrence = buildWorkOccurrenceEvent({ eventId: "fixture:occurrence", now: fixtureNow, payload: {
    scope: fixtureRevisionRef(scope), obligation: fixtureRevisionRef(obligation), executionId: fixtureExecution,
    parentExecutionId: null, childId: "d0.1", variantId: "variant:a", artifact: fixtureRevisionRef(artifact),
    provenance: "observed", state: "completed", labels: { sessionId: "session", branchLeafId: "leaf",
      toolCallId: null, taskId: null, workspaceId: null, definitionDigest: null, configurationDigest: null,
      modelId: null, effortId: null },
  } });
  const claim = buildWorkAcceptanceEvent({ eventId: "fixture:claim", now: fixtureNow, payload: {
    authorityId: "fixture-controller", binding: { ...binding, scope: fixtureRevisionRef(scope),
      snapshot: { id: snapshot.payload.snapshot.snapshotId, digest: snapshot.payload.snapshot.digest },
      artifactDigest: fixtureDigest, evidence: [{ id: "fixture:evidence", digest: fixtureDigest, event: fixtureEventRef(occurrence) }],
    },
  } });
  const events = [scope, policy, artifact, intent, obligation, snapshot, occurrence, claim];
  return { scope, policy, artifact, intent, obligation, snapshot, occurrence, claim, events };
}
export type FixtureRevisionChange = "scope" | "intent" | "obligation" | "artifact" | "policy";

/** Five fixed Task 1 worlds, not a configurable graph or an incoming-claim approval factory. */
export function revisionRevalidationFixture(primary: FixtureRevisionChange) {
  if (!["scope", "intent", "obligation", "artifact", "policy"].includes(primary)) throw new TypeError("unknown fixture world");
  const base = walkingFixture(), prefix = `revalidation:${primary}`;
  const current = { scope: base.scope, intent: base.intent, obligation: base.obligation, artifact: base.artifact, policy: base.policy };
  const successor = (name: FixtureRevisionChange, patch: Partial<Omit<WorkRevision, "digest">> = {}) => {
    const prior = base[name], { digest: _, ...body } = mutableFixture(prior.payload.revision);
    return buildWorkRevisionEvent({ eventId: `${prefix}:${name}:2`, now: fixtureNow, revision: {
      ...body, revision: 2, predecessor: fixtureRevisionRef(prior),
      contentDigest: name === primary ? "c".repeat(64) : body.contentDigest, ...patch,
    } });
  };
  // Stable scopeId is unchanged. Policy/artifact bodies have no scope-revision reference.
  if (primary === "scope") current.scope = successor("scope");
  if (primary === "policy") current.policy = successor("policy");
  if (primary === "artifact") current.artifact = successor("artifact");
  if (primary === "scope" || primary === "intent") current.intent = successor("intent", { parent: fixtureRevisionRef(current.scope) });
  if (primary !== "artifact") current.obligation = successor("obligation", {
    parent: fixtureRevisionRef(current.intent), policy: fixtureRevisionRef(current.policy),
  });
  const binding = { intent: fixtureRevisionRef(current.intent), obligation: fixtureRevisionRef(current.obligation),
    artifact: fixtureRevisionRef(current.artifact), policy: fixtureRevisionRef(current.policy) };
  const snapshot = buildWorkSnapshotEvent({ eventId: `${prefix}:snapshot`, now: fixtureNow, snapshot: {
    snapshotId: `${prefix}:selected`, scope: fixtureRevisionRef(current.scope),
    revisions: [current.intent, current.obligation, current.artifact, current.policy].map(fixtureRevisionRef), bindings: [binding],
  } });
  // Rebind evidence associations, not execution identity or completion authority. No new launch.
  const occurrence = buildWorkOccurrenceEvent({ eventId: `${prefix}:occurrence`, now: fixtureNow, payload: {
    ...mutableFixture(base.occurrence.payload), scope: fixtureRevisionRef(current.scope),
    obligation: binding.obligation, artifact: binding.artifact,
  } });
  const claim = buildWorkAcceptanceEvent({ eventId: `${prefix}:claim`, now: fixtureNow, payload: {
    authorityId: "fixture-controller", binding: { ...binding, scope: fixtureRevisionRef(current.scope),
      snapshot: { id: snapshot.payload.snapshot.snapshotId, digest: snapshot.payload.snapshot.digest },
      artifactDigest: current.artifact.payload.revision.contentDigest,
      evidence: [{ id: `${prefix}:evidence`, digest: "d".repeat(64), event: fixtureEventRef(occurrence) }],
    },
  } });
  const changes = (Object.keys(current) as FixtureRevisionChange[]).filter(name => current[name] !== base[name]);
  return { base, current, changes, snapshot, occurrence, claim,
    events: [...base.events, ...changes.map(name => current[name]), snapshot, occurrence, claim] };
}

/** FIXTURE TRUST-BOUNDARY SIMULATION. Only the five fixed declarations above; no stream/claim argument. */
export function revisionRevalidationAuthority(primary: FixtureRevisionChange): WorkProjectionContext {
  const expected = revisionRevalidationFixture(primary), ctx = fixtureAuthority();
  ctx.selectedSnapshot = { snapshot: { id: expected.snapshot.payload.snapshot.snapshotId, digest: expected.snapshot.payload.snapshot.digest },
    event: fixtureEventRef(expected.snapshot) };
  ctx.authority!.snapshot = { id: `fixture-authority:revalidation:${primary}`, digest: "e".repeat(64) };
  ctx.authority!.decisions.push({ receiptId: `receipt:revalidation:${primary}`, authorityId: "fixture-controller",
    claim: fixtureEventRef(expected.claim), binding: mutableFixture(expected.claim.payload.binding), decision: "accept" });
  if (primary === "artifact") ctx.authority!.availability.push({ kind: "artifact", id: "artifact", digest: "c".repeat(64), available: true });
  ctx.authority!.availability.push({ kind: "evidence", id: `revalidation:${primary}:evidence`, digest: "d".repeat(64), available: true });
  return ctx;
}

export type FixtureSupportKind = "snapshot" | "revision" | "occurrence" | "acceptance";
/** Four fixed support worlds. No incoming event, binding, stream or claimed authority argument. */
export function supportQuarantineFixture(kind: FixtureSupportKind = "snapshot", aliasReference = false) {
  if (!["snapshot", "revision", "occurrence", "acceptance"].includes(kind) || typeof aliasReference !== "boolean") throw new TypeError("unknown support fixture world");
  const base = walkingFixture(), prefix = `support:${kind}`;
  const delivery = (eventId: string) => {
    if (kind === "snapshot") return buildWorkSnapshotEvent({ eventId, now: fixtureNow, snapshot: {
      snapshotId: "support-only", scope: fixtureRevisionRef(base.scope), revisions: [], bindings: [],
    } });
    if (kind === "revision") {
      const { digest: _, ...body } = mutableFixture(base.artifact.payload.revision);
      return buildWorkRevisionEvent({ eventId, now: fixtureNow, revision: { ...body, id: "support-artifact" } });
    }
    if (kind === "occurrence") return buildWorkOccurrenceEvent({ eventId, now: fixtureNow, payload: mutableFixture(base.occurrence.payload) });
    return buildWorkAcceptanceEvent({ eventId, now: fixtureNow, payload: { ...mutableFixture(base.claim.payload),
      binding: { ...mutableFixture(base.claim.payload.binding), snapshot: { id: "support-old-snapshot", digest: "e".repeat(64) } },
    } });
  };
  const support = delivery(`${prefix}:clean`), referenceAlias = delivery(`${prefix}:reference-alias`);
  const claim = buildWorkAcceptanceEvent({ eventId: `${prefix}:claim:${aliasReference ? "alias" : "clean"}`, now: fixtureNow, payload: {
    authorityId: "fixture-controller", binding: { ...mutableFixture(base.claim.payload.binding),
      evidence: [{ id: "support:bytes", digest: fixtureDigest, event: fixtureEventRef(aliasReference ? referenceAlias : support) }],
    },
  } });
  return { base, support, referenceAlias, claim, events: [...base.events.filter(e => e !== base.claim), support, referenceAlias, claim] };
}
/** FIXTURE TRUST-BOUNDARY SIMULATION. Reconstruct closed expected declarations, never incoming claims. */
export function supportQuarantineAuthority(kind: FixtureSupportKind = "snapshot", aliasReference = false): WorkProjectionContext {
  const expected = supportQuarantineFixture(kind, aliasReference), ctx = fixtureAuthority();
  ctx.authority!.decisions.push({ receiptId: "receipt:support", authorityId: "fixture-controller",
    claim: fixtureEventRef(expected.claim), binding: mutableFixture(expected.claim.payload.binding), decision: "accept" });
  ctx.authority!.availability.push({ kind: "evidence", id: "support:bytes", digest: fixtureDigest, available: true });
  return ctx;
}

export const layoutSimulation = "fixture trust-boundary simulation; for selected snapshot; under fixture authority";
export const layoutExecutions = ["exec:00000000-0000-4000-8000-000000000021", "exec:00000000-0000-4000-8000-000000000022"] as const;
/** Independent expected declarations for the generic wire demonstration. No runtime dispatch. */
export function layoutFixture() {
  const revision = (kind: WorkRevision["kind"], id: string, patch: Partial<Omit<WorkRevision, "digest">> = {}) =>
    buildWorkRevisionEvent({ eventId: `${id}:1`, now: fixtureNow, revision: {
      kind, id, scopeId: "layout", revision: 1, predecessor: null, contentDigest: fixtureDigest,
      parent: null, dependencies: [], ownerId: "layout-owner", permittedEffects: [], policy: null, ...patch,
    } });
  const scope = revision("scope", "layout"), policy = revision("policy", "layout-policy"), artifact = revision("artifact", "layout-image");
  const goal = revision("goal", "layout-goal", { parent: fixtureRevisionRef(scope) });
  const intent = revision("node", "layout-options", { parent: fixtureRevisionRef(goal) });
  const obligation = revision("obligation", "layout-choice", { parent: fixtureRevisionRef(intent), policy: fixtureRevisionRef(policy) });
  const revisions = [scope, policy, artifact, goal, intent, obligation];
  const binding = { intent: fixtureRevisionRef(intent), obligation: fixtureRevisionRef(obligation), artifact: fixtureRevisionRef(artifact), policy: fixtureRevisionRef(policy) };
  const snapshot = buildWorkSnapshotEvent({ eventId: "layout:snapshot", now: fixtureNow, snapshot: {
    snapshotId: "layout-selected", scope: fixtureRevisionRef(scope), revisions: revisions.slice(1).map(fixtureRevisionRef), bindings: [binding],
  } });
  const occurrences = ["a", "b", "c"].map((variant, i) => buildWorkOccurrenceEvent({ eventId: `layout:observation:${variant}`, now: fixtureNow, payload: {
    scope: fixtureRevisionRef(scope), obligation: binding.obligation, executionId: layoutExecutions[i === 2 ? 1 : 0],
    parentExecutionId: null, childId: "layout-designer", variantId: `layout:${variant}`, artifact: binding.artifact,
    provenance: "observed", state: "completed", labels: { sessionId: i === 2 ? "layout-session:b" : "layout-session:a",
      branchLeafId: i === 2 ? "layout-leaf:b" : "layout-leaf:a", toolCallId: null, taskId: null, workspaceId: null,
      definitionDigest: null, configurationDigest: null, modelId: null, effortId: null },
  } }));
  const payload = { authorityId: "layout-controller", binding: { ...binding, scope: fixtureRevisionRef(scope),
    snapshot: { id: snapshot.payload.snapshot.snapshotId, digest: snapshot.payload.snapshot.digest }, artifactDigest: fixtureDigest,
    evidence: [{ id: "layout-proof", digest: "d".repeat(64), event: fixtureEventRef(occurrences[0]) }],
  } };
  const claim = buildWorkAcceptanceEvent({ eventId: "layout:claim", now: fixtureNow, payload });
  const secondClaim = buildWorkAcceptanceEvent({ eventId: "layout:claim:second", now: fixtureNow, payload });
  return { scope, policy, artifact, goal, intent, obligation, revisions, snapshot, occurrences, claim, secondClaim,
    events: [...revisions, snapshot, ...occurrences, claim] };
}
/** Fixed positive controller; never accepts a stream, event, arbitrary binding or authority label. */
export function layoutAuthority(): WorkProjectionContext {
  const expected = layoutFixture();
  return { selectedSnapshot: { snapshot: mutableFixture(expected.claim.payload.binding.snapshot), event: fixtureEventRef(expected.snapshot) },
    authority: { snapshot: { id: "layout-fixture-authority", digest: "e".repeat(64) }, decisions: [
      { receiptId: "layout-receipt", authorityId: "layout-controller", claim: fixtureEventRef(expected.claim), binding: mutableFixture(expected.claim.payload.binding), decision: "accept" },
      { receiptId: "layout-receipt:second", authorityId: "layout-controller", claim: fixtureEventRef(expected.secondClaim), binding: mutableFixture(expected.secondClaim.payload.binding), decision: "accept" },
    ], availability: [{ kind: "artifact", id: "layout-image", digest: fixtureDigest, available: true },
      { kind: "evidence", id: "layout-proof", digest: "d".repeat(64), available: true }] } };
}
export function layoutAssociationFixture() {
  const base = layoutFixture(), { digest: _, ...body } = mutableFixture(base.obligation.payload.revision);
  const other = buildWorkRevisionEvent({ eventId: "layout-secondary:1", now: fixtureNow, revision: { ...body, id: "layout-secondary" } });
  const firstBinding = base.snapshot.payload.snapshot.bindings[0], secondBinding = { ...firstBinding, obligation: fixtureRevisionRef(other) };
  const snapshot = buildWorkSnapshotEvent({ eventId: "layout:shared:snapshot", now: fixtureNow, snapshot: {
    snapshotId: "layout-shared", scope: fixtureRevisionRef(base.scope), revisions: [...base.revisions.slice(1), other].map(fixtureRevisionRef), bindings: [firstBinding, secondBinding],
  } });
  const occurrence = buildWorkOccurrenceEvent({ eventId: "layout:shared:occurrence", now: fixtureNow, payload: {
    ...base.occurrences[0].payload, obligation: fixtureRevisionRef(other), variantId: "layout:secondary",
  } });
  const claim = buildWorkAcceptanceEvent({ eventId: "layout:shared:claim", now: fixtureNow, payload: { authorityId: "layout-controller", binding: {
    ...mutableFixture(base.claim.payload.binding), snapshot: { id: snapshot.payload.snapshot.snapshotId, digest: snapshot.payload.snapshot.digest },
  } } });
  const otherClaim = buildWorkAcceptanceEvent({ eventId: "layout:shared:other-claim", now: fixtureNow, payload: { authorityId: "layout-controller", binding: {
    ...claim.payload.binding, obligation: fixtureRevisionRef(other), evidence: [{ id: "layout-secondary-proof", digest: "d".repeat(64), event: fixtureEventRef(occurrence) }],
  } } });
  return { base, other, snapshot, occurrence, claim, otherClaim,
    events: [...base.revisions, other, snapshot, base.occurrences[0], occurrence, claim, otherClaim] };
}
export function layoutAssociationAuthority(): WorkProjectionContext {
  const expected = layoutAssociationFixture(), ctx = layoutAuthority();
  ctx.selectedSnapshot = { snapshot: mutableFixture(expected.claim.payload.binding.snapshot), event: fixtureEventRef(expected.snapshot) };
  ctx.authority!.decisions = [
    { receiptId: "layout-shared-receipt", authorityId: "layout-controller", claim: fixtureEventRef(expected.claim), binding: mutableFixture(expected.claim.payload.binding), decision: "accept" },
    { receiptId: "layout-secondary-receipt", authorityId: "layout-controller", claim: fixtureEventRef(expected.otherClaim), binding: mutableFixture(expected.otherClaim.payload.binding), decision: "accept" },
  ];
  ctx.authority!.availability.push({ kind: "evidence", id: "layout-secondary-proof", digest: "d".repeat(64), available: true });
  return ctx;
}
export type LayoutRevisionChange = FixtureRevisionChange | "snapshot";
/** Closed successor worlds; rebase the actual scope -> goal -> node -> obligation chain. */
export function layoutSuccessorFixture(primary: LayoutRevisionChange) {
  if (!["scope", "intent", "obligation", "artifact", "policy", "snapshot"].includes(primary)) throw new TypeError("unknown layout successor world");
  const base = layoutFixture(), current = { scope: base.scope, goal: base.goal, intent: base.intent, obligation: base.obligation, artifact: base.artifact, policy: base.policy };
  const successor = (name: keyof typeof current, patch: Partial<Omit<WorkRevision, "digest">> = {}) => {
    const prior = base[name], { digest: _, ...body } = mutableFixture(prior.payload.revision);
    return buildWorkRevisionEvent({ eventId: `layout:${primary}:${name}:2`, now: fixtureNow, revision: {
      ...body, revision: 2, predecessor: fixtureRevisionRef(prior), contentDigest: name === primary ? "c".repeat(64) : body.contentDigest, ...patch,
    } });
  };
  if (primary === "scope") { current.scope = successor("scope"); current.goal = successor("goal", { parent: fixtureRevisionRef(current.scope) }); }
  if (primary === "scope" || primary === "intent") current.intent = successor("intent", { parent: fixtureRevisionRef(current.goal) });
  if (primary === "artifact") current.artifact = successor("artifact");
  if (primary === "policy") current.policy = successor("policy");
  if (!["artifact", "snapshot"].includes(primary)) current.obligation = successor("obligation", { parent: fixtureRevisionRef(current.intent), policy: fixtureRevisionRef(current.policy) });
  const binding = { intent: fixtureRevisionRef(current.intent), obligation: fixtureRevisionRef(current.obligation), artifact: fixtureRevisionRef(current.artifact), policy: fixtureRevisionRef(current.policy) };
  const snapshot = buildWorkSnapshotEvent({ eventId: `layout:${primary}:snapshot`, now: fixtureNow, snapshot: {
    snapshotId: `layout:${primary}:selected`, scope: fixtureRevisionRef(current.scope), revisions: [current.policy, current.artifact, current.goal, current.intent, current.obligation].map(fixtureRevisionRef), bindings: [binding],
  } });
  const occurrences = base.occurrences.map((e, i) => buildWorkOccurrenceEvent({ eventId: `layout:${primary}:observation:${i}`, now: fixtureNow, payload: {
    ...e.payload, scope: fixtureRevisionRef(current.scope), obligation: binding.obligation, artifact: binding.artifact,
  } }));
  const claim = buildWorkAcceptanceEvent({ eventId: `layout:${primary}:claim`, now: fixtureNow, payload: { authorityId: "layout-controller", binding: {
    ...binding, scope: fixtureRevisionRef(current.scope), snapshot: { id: snapshot.payload.snapshot.snapshotId, digest: snapshot.payload.snapshot.digest },
    artifactDigest: current.artifact.payload.revision.contentDigest, evidence: [{ id: `layout:${primary}:proof`, digest: "d".repeat(64), event: fixtureEventRef(occurrences[0]) }],
  } } });
  const changes = (Object.keys(current) as (keyof typeof current)[]).filter(k => current[k] !== base[k]);
  return { base, current, changes, snapshot, occurrences, claim, events: [...base.events, ...changes.map(k => current[k]), snapshot, ...occurrences, claim] };
}
export function layoutSuccessorAuthority(primary: LayoutRevisionChange): WorkProjectionContext {
  const expected = layoutSuccessorFixture(primary), ctx = layoutAuthority();
  ctx.selectedSnapshot = { snapshot: mutableFixture(expected.claim.payload.binding.snapshot), event: fixtureEventRef(expected.snapshot) };
  ctx.authority!.snapshot = { id: `layout-fixture-authority:${primary}`, digest: "e".repeat(64) };
  ctx.authority!.decisions.push({ receiptId: `layout-receipt:${primary}`, authorityId: "layout-controller", claim: fixtureEventRef(expected.claim), binding: mutableFixture(expected.claim.payload.binding), decision: "accept" });
  if (primary === "artifact") ctx.authority!.availability.push({ kind: "artifact", id: "layout-image", digest: "c".repeat(64), available: true });
  ctx.authority!.availability.push({ kind: "evidence", id: `layout:${primary}:proof`, digest: "d".repeat(64), available: true });
  return ctx;
}

export function fixtureAuthority(): WorkProjectionContext {
  // Reconstruct fixed expected declarations independently of whichever stream is under test.
  const expected = walkingFixture();
  return {
    selectedSnapshot: { snapshot: { id: "fixture-selected", digest: expected.snapshot.payload.snapshot.digest },
      event: fixtureEventRef(expected.snapshot) },
    authority: { snapshot: { id: "fixture-authority", digest: "b".repeat(64) },
      decisions: [{ receiptId: "receipt:a", authorityId: "fixture-controller", claim: fixtureEventRef(expected.claim),
        binding: mutableFixture(expected.claim.payload.binding), decision: "accept" }],
      availability: [{ kind: "artifact", id: "artifact", digest: fixtureDigest, available: true },
        { kind: "evidence", id: "fixture:evidence", digest: fixtureDigest, available: true }],
    },
  };
}
